version: '3.4'

services:
  comparis.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ComparisConnectionString=Server=comparisdb;Database=ComparisDb;User Id=sa;Password=admin1234;"
      - "Jaeger=JAEGER_SERVICE_NAME=jagerservice"
      - "Jaeger=JAEGER_AGENT_HOST=jagerservice"
      - "Jaeger=JAEGER_AGENT_PORT=6831"
      - "Jaeger=JAEGER_SAMPLER_TYPE=const"
      - "Jaeger=JAEGER_SAMPLER_PARAM=1"
    depends_on:
      - comparisdb
    ports:
      - "8020:80"

  comparisdb:
    container_name: comparisdb
    environment:
      SA_PASSWORD: "admin1234"
      ACCEPT_EULA: "Y"
    restart: always
    ports: 
      - "1433:1433"

  jagerservice:
    container_name: jagerservice
    restart: on-failure
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411